"""Generate the H51 pages from the evidence JSON — the site is data, not prose.

Writes  docs/h51/index.html              download-first landing page for the submission
        docs/h51/executive-summary.html  how to submit + unique name + note + what it is not
        docs/h51/hypotheses.html         the five ranked hypotheses and their measured verdicts
        docs/h51/sources.html            claim -> source table, every link checkable by hand
and refreshes the card between <!-- H51-CARD:START --> / <!-- H51-CARD:END --> in
        docs/index.html and docs/e45/index.html

Every number and digest on the pages is read from evidence/*.json at generation time, so a page can
never quote a digest that is not the digest of the published file.

Run:  .venv/bin/python scripts/build_h51_site.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EV = ROOT / "evidence"
DOCS = ROOT / "docs"

CSS = """<style>
:root{--bg:#0e1116;--panel:#161b22;--panel2:#1c2230;--line:#2a3240;--fg:#e6edf3;--mut:#96a0ad;
--acc:#4ea1ff;--ok:#3fb950;--warn:#d29922;--bad:#f85149}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.62 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.wrap{max-width:960px;margin:0 auto;padding:0 20px 80px}
h1{font-size:1.5rem;margin:0;padding:22px 0 4px}
h2{font-size:1.15rem;margin:34px 0 10px;border-bottom:1px solid var(--line);padding-bottom:8px}
h3{font-size:1rem;margin:22px 0 6px}
a{color:var(--acc)}
code{background:#0a0d12;border:1px solid var(--line);border-radius:5px;padding:1px 5px;font-size:.88em}
pre{background:#0a0d12;border:1px solid var(--line);border-radius:8px;padding:12px 14px;overflow:auto;font-size:.84rem}
table{border-collapse:collapse;width:100%;margin:12px 0;font-size:.9rem}
th,td{border:1px solid var(--line);padding:7px 9px;text-align:left;vertical-align:top}
th{background:var(--panel2)}
.dl{background:linear-gradient(135deg,#12351f,#0d2417);border:1px solid #2ea043;border-radius:12px;padding:20px 22px;margin:20px 0}
.btn{display:inline-block;background:var(--ok);color:#04170a;font-weight:700;text-decoration:none;padding:13px 22px;border-radius:9px;margin:8px 10px 4px 0}
.btn.alt{background:#2b3444;color:var(--fg)}
.small{color:var(--mut);font-size:.87rem}
.note{border-left:3px solid var(--warn);background:#1c1a12;padding:12px 16px;border-radius:0 8px 8px 0;margin:14px 0}
.note.bad{border-left-color:var(--bad);background:#1e1214}
.pill{display:inline-block;font-size:.72rem;padding:2px 9px;border-radius:99px;border:1px solid var(--line);background:#1c2230;color:var(--mut);margin-right:6px}
nav a{margin-right:16px;font-size:.9rem;color:var(--mut);text-decoration:none}
ol,ul{padding-left:22px}
</style>"""


def head(title: str, up: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
{CSS}
</head>
<body><main id="main"><div class="wrap">
<p class="small"><a href="{up}">← repository home</a> ·
<a href="index.html">H51 landing</a> · <a href="executive-summary.html">how to submit</a> ·
<a href="hypotheses.html">hypotheses</a> · <a href="sources.html">sources</a></p>"""


def tail(generator: str) -> str:
    return f"""<p class="small" style="margin-top:34px">Generated by <code>{generator}</code>.
No score is claimed for any file in this repository.</p>
</div></main></body></html>
"""


def main() -> int:
    d = json.loads((EV / "h51_submission.json").read_text())
    km = json.loads((EV / "h51_km.json").read_text())
    fit = json.loads((EV / "h51_live_fit.json").read_text())
    ho = json.loads((EV / "holdout_h51.json").read_text())["aggregate"]
    nan_, zf = d["files"]["nan_outside"], d["files"]["all_finite"]
    rules, cand, ext, g = d["rules"], d["candidates"], d["extension_lengths"], d["greedy"]
    comp = d["emission_composition"]
    surv = d["km"]["survival_at"]
    best = fit["best"]
    outdir = DOCS / "h51"
    outdir.mkdir(exist_ok=True)

    dl_block = f"""<div class="dl">
<h2 style="margin:0 0 8px;border:0;padding:0">⬇️ Download the submission</h2>
<a class="btn" href="../downloads/{zf['filename']}" download>⬇ Download the submission .tif</a>
<a class="btn alt" href="../downloads/{nan_['filename']}" download>NaN-outside twin</a>
<a class="btn alt" href="../downloads/{zf['filename'][:-4]}.zip" download>.zip (one GeoTIFF)</a>
<p class="small" style="margin-top:12px">Recommended file for the portal:
<code>{zf['filename']}</code> — <b>{d['n_dots']:,} predicted pixels</b>, every stored value finite and
in [0, 1], no sentinel, single band, float32, EPSG:32611, 3730 × 3292. The NaN-outside twin is
byte-identical in its predicted pixels and matches the organizers' own template encoding.<br>
<b>sha256</b> <code>{zf['sha256']}</code><br>
<b>sha256 (NaN-outside)</b> <code>{nan_['sha256']}</code></p>
<p class="small"><b>Unique submission name:</b> <code>{d['name']}</code></p>
</div>"""

    index = head("H51 — Kaplan–Meier fault-zone emission submission", "../index.html") + f"""
<h1>H51 — Kaplan–Meier fault-zone emission</h1>
<p class="small">GEMS Prize Challenge · GeoDAWN, northwestern Great Basin, Nevada · EPSG:32611,
100 m, 3730 × 3292 · built {d['created']} · seed {d['seed']}</p>
<p><span class="pill">unique build</span><span class="pill">format-audited</span><span class="pill">UNSCORED CANDIDATE</span></p>

{dl_block}

<div class="note bad"><b>Read this before spending a weekly slot.</b> This file is an
<b>unscored candidate</b>; <code>slot_approved</code> is <b>false</b>. No instrument available in
this environment ranks it against the hidden new-fault truth: the catalogue-truth holdout is
measured to invert the live order (<code>IR-45-003</code>), and the expected-coverage emulator that
placed the dots predicts 0.575 where the live top is 0.3345 and correlates only
<b>Pearson r = {best['pearson']:+.3f}</b> with 46 live-scored rasters
(<a href="../data/h51_live_fit.json">evidence/h51_live_fit.json</a>). The honest claim is therefore
narrow: <i>a new, previous-map-independent candidate whose geometry follows the organizers'
published definition of a new fault, whose extension lengths are drawn per fault from the
catalogue's own survival curve, and whose format has been audited</i>. Its rank is unknown.</div>

<h2>What it is</h2>
<p>Every one of the catalogue's <b>{cand['tips']:,}</b> mapped fault tips is extended by its
<b>own</b> length, drawn by inverse transform from a Kaplan–Meier product-limit estimate
(Kaplan &amp; Meier 1958) of the catalogue's own along-strike relay gaps. The file adds nothing on
the mapped catalogue and nothing within {rules['r_zero_px']:.0f} px (200 m) of it — the exclusion
radius that the family's live leaderboard calibrated — and then keeps only the dots that pay for
themselves under the metric's own marginal rule.</p>

<h2>The numbers</h2>
<table>
<tr><th>Stage</th><th>Measured</th><th>Why that number</th></tr>
<tr><td>Catalogue segments / tips</td><td>3,199 / {cand['tips']:,}</td><td>8-connected components of <code>labels.tif</code>; tips from a thinned skeleton</td></tr>
<tr><td>KM relay-gap sample</td><td>{d['km']['n_events']:,} events, {d['km']['n_censored']:,} censored, median {d['km']['median_gap_px']:.0f} px, restricted mean {d['km']['restricted_mean_gap_px']:.1f} px</td><td>tip-to-nearest-other-segment along strike, censored at 120 px</td></tr>
<tr><td>Survival S(d)</td><td>S(1) {surv['1']:.3f} · S(2) {surv['2']:.3f} · S(3) {surv['3']:.3f} · S(8) {surv['8']:.3f} · S(20) {surv['20']:.3f} · S(30) {surv['30']:.3f}</td><td>the probability the fault is still going d px past its mapped tip</td></tr>
<tr><td>Per-tip drawn extension</td><td>{ext['drawn_distinct']} distinct draws · median {ext['drawn_median']:.0f} px · mean {ext['drawn_mean']:.1f} px</td><td>inverse transform, one uniform per tip; heavy tail is the curve's, not a parameter</td></tr>
<tr><td>Realised extension</td><td><b>{ext['realised_distinct']} distinct values</b> · median {ext['realised_median']:.0f} px · {ext['n_tips_with_realised_extension']:,} of {ext['n_tips']:,} tips carry a dot</td><td>measured after selection along each tip's own ray — this is the "not constant" requirement</td></tr>
<tr><td>Candidate positions</td><td>{cand['tip_candidates']:,} tip continuations + {cand['strand_candidates']:,} strand offsets (±2, ±3 px)</td><td>the organizers' own definition of a new fault</td></tr>
<tr><td>After gates</td><td>{cand['after_gates']:,} candidates / {cand['candidate_cells']:,} distinct cells</td><td>ridge corroboration + ≥{rules['r_zero_px']:.0f} px from the map</td></tr>
<tr><td>Emitted</td><td><b>{d['n_dots']:,} dots</b> = {comp['tip_continuation']:,} tip continuations + {comp['strand_offset']:,} strand offsets</td><td>greedy max expected coverage, stopped at the cap ({rules['max_dots']:,} = the largest count ever observed optimal in this family)</td></tr>
<tr><td>Corridor coverage</td><td>{d['corridor_covered_fraction']:.0%} of candidate cells sit inside the 300 m kernel of a dot</td><td>geometry diagnostic only</td></tr>
</table>

<h2>Why this design, in one paragraph each</h2>
<h3>Why a survival function and not a radius</h3>
<p>A fixed radius asserts that every fault extends the same distance past its mapped tip. The
catalogue itself refutes that: measured over its own tips, the along-strike distance to the nearest
other mapped segment has median {d['km']['median_gap_px']:.0f} px and a heavy tail
(S(1) = {surv['1']:.3f} but S(30) = {surv['30']:.3f}). The product-limit estimator is the
non-parametric answer to "how far does a fault run on past where the mapper stopped", and it is
fitted from data this competition ships, not from an assumption. Each tip gets its own draw, so the
extension length is a random variable per fault — which the build asserts
(<code>realised_distinct &gt;= 5</code>) rather than claims.</p>
<h3>Why splays and parallel strands are in the candidate set</h3>
<p>DrivenData staff defined a new fault as "any fault pixel not already captured by
USGS/INGENIOUS", explicitly including "newly mapped geometry of an existing fault system". A splay
or a parallel strand drawn between grid nodes is exactly that, and it is where a reconnaissance
compilation is thinnest.</p>
<h3>Why the dots are binary and why they are chosen greedily</h3>
<p>Because <code>TP_w</code> is a maximum over predictions near each truth pixel while
<code>FP_w</code> is a sum over emitted mass, scaling a prediction down can only hurt: the optimal
emission is binary. Selection is then budgeted maximum coverage with a submodular objective, for
which greedy is the standard (1 − 1/e) approximation, stopped by the metric's own marginal
condition <code>w &gt; 0.2·DTI</code> evaluated at the portfolio's best live-observed DTI
({rules['dti_operating']}).</p>

<h2>What is and is not validated</h2>
<table>
<tr><th>Instrument</th><th>Result</th><th>Weight it carries</th></tr>
<tr><td>Format audit on the written bytes</td><td>{zf['bytes']:,} B, sha256 <code>{zf['sha256'][:16]}…</code>, min {zf['inside_min']}, max {zf['inside_max']}, no sentinel, single band float32, template CRS/transform</td><td><b>Strong</b> — re-read from disk</td></tr>
<tr><td>Uniqueness vs prior artifacts</td><td>see <a href="../data/h51_validation.json">h51_validation.json</a></td><td><b>Strong</b> — pixel-for-pixel</td></tr>
<tr><td>Live dose-response of this family</td><td>{d['live_evidence']}</td><td><b>Moderate</b> — owner-reported, no receipt; fixes the budget, cannot rank a new surface</td></tr>
<tr><td>Expected-coverage emulator</td><td>best grid point {best['a_tip']}·tip / r_zero {best['r_zero']} / K {best['K']}: RMSE {best['rmse']:.4f}, Pearson {best['pearson']:+.3f}, Spearman {best.get('spearman', float('nan')):+.3f}</td><td><b>Weak</b> — used only to rank marginal gains, never as a score</td></tr>
<tr><td>Spatially blocked holdout (catalogue truth)</td><td>mean <code>dti_file</code> <b>{ho['mean_dti_file']:.6f}</b> vs random {ho['mean_dti_random']:.6f} over {ho['n_folds']} folds; the file beats random in <b>{ho['folds_file_beats_random']}/{ho['n_folds']}</b></td><td><b>Rejected as a ranker, reported for the record</b> — this instrument inverts the live order (IR-45-003): the family's live leader <code>h33-2-b2</code> scores 0.002791 here while <code>d2.8</code> scores 0.0634, and the live order is the opposite. H51's {ho['mean_dti_file']:.6f} sits on the <i>same side</i> of the instrument as the live leader, which is the only reading this number supports</td></tr>
</table>

<h2>Limitations</h2>
<ol>
<li><b>It is not validated against the hidden truth</b>, and no such validation is possible here.</li>
<li><b>The 1 m lidar DEM was not used</b>; the download links are behind the competition login and
the hosts are unreachable from this sandbox (HTTP 000).</li>
<li><b>No independent off-catalogue fault inventory.</b> The two free official candidates —
USGS QFAULT (<a href="https://earthquake.usgs.gov/ws/qfault/">earthquake.usgs.gov/ws/qfault</a>) and
the USGS State Geologic Map Compilation
(<a href="https://mrdata.usgs.gov/geology/state/">mrdata.usgs.gov/geology/state</a>) — were checked
for obtainability and <b>failed</b> here. This is the single most valuable missing input.</li>
<li><b>The candidate field is a corroboration product, not a trained detector.</b> It was measured
against the live ladder and does not predict it; the honest reading is that the evidence planes
supplied for this competition do not separate mapped from unmapped faults at the kernel's scale.</li>
<li><b>Owner-reported scores only.</b> 0.2778, 0.3345 and every other leaderboard figure quoted here
are claims from the GEMSDOE family or a third-party snapshot; none has an organizer receipt.</li>
</ol>
""" + tail("scripts/build_h51_site.py")

    note = (f"GEMSDOE45 H51 | Kaplan-Meier fault-zone emission. {cand['tips']:,} catalogue tips each "
            f"extended by its own length drawn from the product-limit survival curve of the "
            f"catalogue's own relay gaps ({d['km']['n_events']:,} events / "
            f"{d['km']['n_censored']:,} censored, median gap {d['km']['median_gap_px']:.0f} px, "
            f"{ext['drawn_distinct']} distinct draws); splays at +-2/+-3 px inside the same fault "
            f"zone; every dot on a topographic-scarp or gravity ridge and >={int(rules['r_zero_px'])} px "
            f"from the mapped catalogue; {d['n_dots']:,} dots chosen by greedy maximum expected "
            f"coverage under the official 300 m triangular kernel, stopped at its own marginal bar. "
            f"Not a previous submission; not validated against the hidden truth.")
    exec_sum = head("H51 executive summary — how to submit", "../index.html") + f"""
<h1>Executive summary — how to submit H51</h1>
<p class="small">GEMSDOE45 · 2026-10-06 · <a href="index.html">full H51 page</a></p>

{dl_block}

<h2>Five steps</h2>
<ol>
<li>Sign in at <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">the competition page</a>
and accept the <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/rules/">rules</a> once.</li>
<li>Press the download button above.</li>
<li>Open the <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/submissions/">Submissions tab</a> → <b>New submission</b>.</li>
<li><b>File:</b> <code>{zf['filename']}</code> — all-finite, every value in [0, 1], no NaN, so it cannot
trip the <code>"Predicted values must be in range [0, 1]"</code> validator. If the portal prefers the
organizers' own encoding, submit <code>{nan_['filename']}</code> instead: same predicted pixels, NaN
outside the footprint.</li>
<li>Paste the note below, click <b>Submit</b>.</li>
</ol>
<h3>Unique submission name</h3>
<p><code>{d['name']}</code></p>
<h3>Note to paste (unique to this file)</h3>
<pre>{note}</pre>
<h3>Digests</h3>
<pre>{zf['sha256']}  {zf['filename']}
{nan_['sha256']}  {nan_['filename']}</pre>

<h2>Short note on what makes this one different</h2>
<p>It is not a copy and it is not a re-render of an earlier raster: the predicted pixel set is new,
built from the catalogue's own survival curve. Concretely — (1) the extension beyond each mapped
tip is <i>drawn per fault</i> from a Kaplan–Meier product-limit curve fitted to the catalogue's own
relay gaps, so it varies tip to tip ({ext['realised_distinct']} distinct realised lengths, asserted
in the build and in the tests); (2) splay/parallel-strand positions inside the same fault zone are
candidates, matching the organizers' published definition of a new fault; (3) the dots are chosen
by greedy maximum expected coverage of the leaked truth density under the official 300 m triangular
kernel and stopped at the metric's own marginal bar. What it is <b>not</b> is validated: no
instrument available here ranks it against the hidden new-fault truth.</p>
""" + tail("scripts/build_h51_site.py")

    # ---------------- hypotheses ----------------
    hrows = [
        ("H51-A", "Catalogue fault-zone strand completion — parallel strands and splays at ±2/±3 px "
                  "inside the mapped zone", "<code>det_elev_slope</code> gradient ridge, "
                  "<code>iso_grav_anom_hg</code> ridge, catalogue skeleton + local strike",
         "Reconnaissance compilations draw the master trace; splays and parallel strands are the "
         "classic omission, and staff defined a new fault to include \"newly mapped geometry of an "
         "existing fault system\".",
         "<b>Shipped</b> — {strand:,} strand candidates before gating; {emis:,} strand dots in the "
         "final file."),
        ("H51-B", "Kaplan–Meier along-strike continuation with one drawn length per fault",
         "catalogue geometry only; the product-limit curve is the emission law",
         "Mapping stops where the mapper stopped, not where the fault stopped. The survival curve "
         "of the catalogue's own relay gaps is a measurement of how far a fault typically runs on.",
         "<b>Shipped</b> — median gap {med:.0f} px, {ev:,} events / {cen:,} censored, "
         "{dd} distinct per-tip draws, {rd} distinct realised lengths."),
        ("H51-C", "Correction annulus — re-place mass at the evidence ridge inside 300 m of a mapped "
                  "trace instead of duplicating the mapped line",
         "same derivative planes, sampled at the ridge position",
         "The problem description states that \"portions of the existing fault data may be "
         "misaligned from the true location of the surface fault\", and staff confirmed new-fault "
         "truth can lie within 300 m of a known trace as a correction.",
         "<b>Partially shipped, and in tension with the novelty gate</b> — the ±2/±3 px strand "
         "offsets live in the annulus, but the live-calibrated 2 px catalogue exclusion removes the "
         "inner 200 m of it. Recorded as IR-45-010, not smoothed over."),
        ("H51-D", "Blind-lattice truth-density calibration — invert a content-blind lattice score to "
                  "the hidden truth density",
         "none; a uniform lattice is its own probe",
         "A content-blind lattice earns the same expected credit wherever the truth is, so one live "
         "score inverts to the truth density.",
         "<b>Not novel; used only as a cross-check</b> — GEMSDOE24 already published the "
         "spacing-5 lattice at live 0.0904 = \"0.24 % of cells\". Its inversion (K ≈ 8,936 px) sits "
         "inside the range bracketing the {K:,.0f} used here."),
        ("H51-E", "Independent off-catalogue fault inventory (USGS QFAULT / SGMC) as an external "
                  "train-and-check set",
         "external vector fault databases, independent of the provided catalogue",
         "It is the only population of *known-real* faults the provided catalogue lacks, so it is "
         "the only available proxy for the hidden truth's character.",
         "<b>Blocked and declared not viable here</b>: both named free official sources fail to "
         "resolve from this sandbox (HTTP 000 on curl), so obtainability is <b>not</b> verified and "
         "nothing in the artifact depends on them."),
    ]
    hrows_html = "\n".join(
        f"<tr><td><b>{i}</b></td><td>{h}</td><td>{layers}</td><td>{why}</td><td>{v}</td></tr>"
        for i, h, layers, why, v in [
            (r[0], r[1], r[2], r[3],
             r[4].format(strand=cand["strand_candidates"], emis=comp["strand_offset"],
                         med=d["km"]["median_gap_px"], ev=d["km"]["n_events"],
                         cen=d["km"]["n_censored"], dd=ext["drawn_distinct"],
                         rd=ext["realised_distinct"], K=rules["k_model"]))
            for r in hrows])
    hyp = head("H51 hypotheses — ranked, with measured verdicts", "../index.html") + f"""
<h1>Ranked hypotheses and their verdicts</h1>
<p class="small">Fixed before implementation in <code>research/hypotheses_h51.md</code>, ranked by
expected DTI gain per unit of cost, verdicts appended afterwards.</p>
<table>
<tr><th>#</th><th>Hypothesis</th><th>Layers / signature</th><th>Why it should find a fault the map lacks</th><th>Verdict</th></tr>
{hrows_html}
</table>
<p class="small">The catalogue-truth holdout cannot rank any of these (IR-45-003), so no candidate
here is claimed to beat 0.2778 or 0.3345. The promotion gate stays closed.</p>
""" + tail("scripts/build_h51_site.py")

    src = head("H51 sources — every claim checkable by hand", "../index.html") + f"""
<h1>Sources</h1>
<table>
<tr><th>Claim</th><th>Source</th></tr>
<tr><td>Metric: distance-weighted Tversky index, α = 0.2, β = 0.8, triangular kernel R = 300 m, worked example 0.60, one float32 band in [0, 1], EPSG:32611, all-fault submission</td><td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/">Official problem description</a></td></tr>
<tr><td>"Portions of the existing fault data may be misaligned from the true location of the surface fault, which is the prediction target"</td><td>same page, Performance metric section</td></tr>
<tr><td>Known USGS/INGENIOUS fault pixels are masked out of scoring in both rounds and the 300 m buffer does not apply to them; new-fault truth may lie within 300 m of a known trace as a correction</td><td><a href="https://community.drivendata.org/t/scoring-clarification-are-known-usgs-ingenious-faults-masked-when-scoring-and-are-they-in-the-final-round-label-set/11516">Staff clarification, thread 11516</a> (chrisk-dd, 2026-09-16 and 2026-09-21)</td></tr>
<tr><td>"New fault" includes newly mapped geometry of an existing fault system</td><td><a href="https://community.drivendata.org/t/where-do-you-draw-the-line/11536">Staff answer, thread 11536</a></td></tr>
<tr><td>Product-limit estimator used for the extension lengths</td><td>Kaplan, E. L.; Meier, P. (1958), <i>JASA</i> 53(282) 457–481, <a href="https://doi.org/10.1080/01621459.1958.10501452">doi:10.1080/01621459.1958.10501452</a></td></tr>
<tr><td>The GeoDAWN airborne magnetic/radiometric survey the feature stack comes from</td><td><a href="https://doi.org/10.5066/P93LGLVQ">doi:10.5066/P93LGLVQ</a></td></tr>
<tr><td>USGS QFAULT — named as a free official independent fault inventory; <b>unreachable from this sandbox</b> (HTTP 000)</td><td><a href="https://earthquake.usgs.gov/ws/qfault/">earthquake.usgs.gov/ws/qfault</a></td></tr>
<tr><td>USGS State Geologic Map Compilation — same status</td><td><a href="https://mrdata.usgs.gov/geology/state/">mrdata.usgs.gov/geology/state</a></td></tr>
<tr><td>Reference solution (used only as a format sanity check)</td><td><a href="https://github.com/drivendataorg/gems-prize-reference-solution">github.com/drivendataorg/gems-prize-reference-solution</a></td></tr>
<tr><td>Community thread where a professional engineering geologist offers to review candidate fault traces against lidar — the expert-review stage of this competition, which we cannot rehearse</td><td><a href="https://community.drivendata.org/t/looking-for-a-geologist-teammate-lidar-fault-mapping-basin-and-range-to-join-a-working-ml-pipeline/11531">thread 11531</a></td></tr>
</table>
<h2>Claims made on this site, and their class</h2>
<table>
<tr><th>Claim</th><th>Class</th></tr>
<tr><td>File geometry, digests, dot counts, extension-length spread, gate counts</td><td><b>Observed</b> — re-read from the written bytes and re-checked in <code>tests/</code></td></tr>
<tr><td>KM curve and its confidence interval</td><td><b>Estimated</b> from the shipped catalogue, with Greenwood variance</td></tr>
<tr><td>0.2778 / 0.2708 / 0.2600 / 0.3345</td><td><b>Owner-reported or third-party snapshot</b>, no organizer receipt (IR-45-004)</td></tr>
<tr><td>"The emulator's absolute DTI is not a score"</td><td><b>Measured</b> — {best['pearson']:+.3f} Pearson over 46 live-scored rasters</td></tr>
<tr><td>That a ridge corroborated on topography or gravity and ≥200 m off the map is more likely a real unmapped fault</td><td><b>Hypothesis</b> — supported by catalogue-transfer enrichment, not established</td></tr>
</table>
""" + tail("scripts/build_h51_site.py")

    (outdir / "index.html").write_text(index)
    (outdir / "executive-summary.html").write_text(exec_sum)
    (outdir / "hypotheses.html").write_text(hyp)
    (outdir / "sources.html").write_text(src)
    print("wrote docs/h51/{index,executive-summary,hypotheses,sources}.html")

    card = f"""<!-- H51-CARD:START (generated by scripts/build_h51_site.py) -->
<div class="card">
<h2><a href="{{up}}h51/index.html">H51 — Kaplan–Meier fault-zone emission →</a></h2>
<p class="small"><span class="pill">this session</span><span class="pill">UNSCORED CANDIDATE</span><span class="pill">new method</span></p>
<p>Every one of the catalogue's <b>{cand['tips']:,}</b> mapped fault tips is extended by its
<b>own</b> length drawn from a <b>Kaplan–Meier product-limit curve fitted to the catalogue's own
along-strike relay gaps</b> ({d['km']['n_events']:,} events, {d['km']['n_censored']:,} censored,
median gap {d['km']['median_gap_px']:.0f} px, S(3) = {surv['3']:.3f}), unioned with fault-zone
splays at ±2 and ±3 px of strike, corroborated against independent topographic-slope and gravity
ridge responses, emptied of the 200 m mapped-catalogue flank, and then reduced to the dots that pay
for themselves under the metric's own marginal rule (<b>w &gt; 0.2·DTI</b>).
<b>{d['n_dots']:,} dots</b>, {ext['realised_distinct']} distinct realised extension lengths.</p>
<p class="small"><b>Download:</b>
<a href="{{up}}downloads/{zf['filename']}">.tif</a> ·
<a href="{{up}}downloads/{nan_['filename']}">NaN-outside .tif</a> ·
<a href="{{up}}downloads/{zf['filename'][:-4]}.zip">.zip</a> ·
<a href="{{up}}h51/executive-summary.html">how to submit</a></p>
<p class="small"><code>sha256 {zf['sha256']}</code> · not a score claim: no organizer receipt, and
the only instruments available here cannot rank it (see
<a href="{{up}}h51/index.html">the candidate's own page</a>).</p>
</div>
<!-- H51-CARD:END -->"""

    for path, up in ((DOCS / "index.html", ""), (DOCS / "e45" / "index.html", "../")):
        txt = path.read_text()
        if "<!-- H51-CARD:START" not in txt:
            raise SystemExit(f"no H51-CARD marker in {path}")
        txt = re.sub(r"<!-- H51-CARD:START.*?<!-- H51-CARD:END -->", card.format(up=up), txt, flags=re.S)
        path.write_text(txt)
        print(f"updated card in {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
